sx_image: xcode9
language: objective-c
cache:
  - bundler
  - cocoapods
branches:
  only:
    - dev
    - master
notifications:
  email: false
before_install:
  - gem install bundler
  - bundle install
script: bundle exec fastlane funky